on: [push, pull_request]

name: 'Analyse shell scripts'

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck on installation scripts
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './installation-scripts'
      env:
        SHELLCHECK_OPTS: -x
    - name: Run ShellCheck on usr/local/bin
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './archiso/airootfs/usr/local/bin'
        ignore: './archiso/airootfs/usr/local/bin/choose-mirror'
      env:
        SHELLCHECK_OPTS: -x
